# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-and-push-api-image:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_ID: sylvan-octagon-268211
      - IMAGE_NAME: skywarn-status-srcares-api-static
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build image
          command: docker build --rm=false -f circleci.dockerfile -t us.gcr.io/$PROJECT_ID/$IMAGE_NAME:$CIRCLE_BUILD_NUM -t us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .
      # https://cloud.google.com/container-registry/docs/pushing
      - run:
          name: Configure gcloud Auth for Docker
          command: gcloud auth configure-docker
      - run:
          name: Setup auth key file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run:
          name: Authenticate with gcloud
          command: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run:
          name: Push new image to gcloud registry
          command: docker push us.gcr.io/$PROJECT_ID/$IMAGE_NAME:$CIRCLE_BUILD_NUM
      - run:
          name: Push to tag latest
          command: docker push us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-and-push-api-image
